#!/bin/bash

# GreenSlot makes SLURM aware of solar energy availability.
# http://www.research.rutgers.edu/~goiri/
# Copyright (C) 2012 Inigo Goiri, Rutgers University
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Store deadline and time
deadline=0
runtime=0
args=""
while [[ $# -gt 0 ]]; do
        case $1 in
                --deadline)
                        deadline=$2
                        shift
                        ;;
                --running)
                        runtime=$2
                        shift
                        ;;
                *)
                        args=$args" "$1
                        ;;
        esac
        shift
done

# Submitting
echo "sbatch -H $args"
jobid=`sbatch -H $args`
if [ $? == 0 ]; then
        jobid=`echo $jobid | cut -d' ' -f4`
        echo $jobid" "$deadline" "$runtime >> /tmp/gslurm
	echo $jobid
        #jobid=`echo $jobid | awk '{print $4}'`
fi
